name: 🛠️ 自动构建 (Commit)

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-build:
    name: 🛠️ 自动构建
    runs-on: ubuntu-22.04
    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v4

      - name: 安装 Gradle (Install Gradle)
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: liberica
          cache: gradle

      - name: 给予 Gradle 包装器执行权限 (Grant execute permission for gradlew)
        run: chmod +x gradlew

      - name: 构建项目 (Build project)
        id: gradle-build
        run: |
          ./gradlew build --no-daemon

      - name: 安装 Python (Set up Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 获取当前版本号 (Get current version)
        id: get-version
        run: |
          echo "version=$(python .github/scripts/parse_version.py)" >> $GITHUB_OUTPUT

      - name: 上传构建产物 (Upload artifacts)
        uses: actions/upload-artifact@v7
        with:
          name: forge
          archive: false
          if-no-files-found: ignore
          path: |
            build/libs/*.jar

      - name: 上传编译结果到 Release (Upload build result to Release)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.get-version.outputs.version }}"
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          omitBodyDuringUpdate: true
          #          body: |
          #            ${{ steps.changelog.outputs.compareurl }}
          #            ${{ steps.changelog.outputs.changelog }}
          artifacts: |
            build/libs/*.jar
