name: 🛠️ 自动构建 (Commit)

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  commit-build:
    name: 🛠️ 自动构建
    runs-on: ubuntu-22.04
    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v6

      - name: 安装 Gradle (Install Gradle)
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: liberica
          cache: gradle

      - name: 给予 Gradle 包装器执行权限 (Grant execute permission for gradlew)
        run: chmod +x gradlew

      - name: 构建项目 (Build project)
        id: gradle-build
        run: |
          ./gradlew build --no-daemon
          version="$(./gradlew -q printModVersion --no-daemon)"
          if [[ -z "${version}" ]]; then
            echo "::error::无法从 printModVersion 任务读取 version，流程终止。"
            exit 1
          fi
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "Detected version: ${version}"

      - name: 上传构建产物 (Upload artifacts)
        uses: actions/upload-artifact@v7
        with:
          name: forge
          archive: false
          if-no-files-found: ignore
          path: build/libs/searchonmcmod-forge-1.12.2-${{ steps.gradle-build.outputs.version }}.jar

      - name: 上传编译结果到 Release (Upload build result to Release)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.gradle-build.outputs.version }}"
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          omitBodyDuringUpdate: true
          #          body: |
          #            ${{ steps.changelog.outputs.compareurl }}
          #            ${{ steps.changelog.outputs.changelog }}
          artifacts: build/libs/searchonmcmod-forge-1.12.2-${{ steps.gradle-build.outputs.version }}.jar
