name: 🚀 发布正式版 (Release)

on:
  workflow_dispatch:
    inputs:
      version:
        description: '输入要发布的版本号（不需要带v）'
        required: true
        type: string
      skip_version_check:
        description: '跳过版本号检查（确认不使用最新发布版本时勾选）'
        type: boolean
        default: false
      mc_1_21_1_21_8:
        description: '发布 1.21-1.21.8 版本'
        type: boolean
        default: false
      mc_1_21_9_1_21_10:
        description: '发布 1.21.9-1.21.10 版本'
        type: boolean
        default: false
      mc_1_20_6:
        description: '发布 1.20.6 版本'
        type: boolean
        default: false
      mc_1_20_x:
        description: '发布 1.20.x 版本'
        type: boolean
        default: false
      mc_1_19_x:
        description: '发布 1.19.x 版本'
        type: boolean
        default: false
      mc_1_18_x:
        description: '发布 1.18.x 版本'
        type: boolean
        default: false
      mc_1_16_5:
        description: '发布 1.16.5 版本'
        type: boolean
        default: false
      mc_1_12_2:
        description: '发布 1.12.2 版本'
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v6

      - name: 得到最新发布版本 (Get latest Release)
        run: |
          latest_version=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: 检查版本号 (Check version)
        if: ${{ !inputs.skip_version_check }}
        run: |
          if [ "v${{ github.event.inputs.version }}" != "$latest_version" ]; then
            echo "输入的版本号 ${GITHUB_EVENT_INPUT_VERSION} 不等于最新发布版本 ${latest_version}，请检查！"
            exit 1
          fi

      - name: 安装 Bun (Set up Bun)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 获取 Release 文件名 (Get Release asset names)
        id: get-release-assets
        run: |
          asset_names=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ github.event.inputs.version }}" | jq -r '.assets[].name')
          echo "asset_names<<EOF" >> $GITHUB_OUTPUT
          echo "$asset_names" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 获取选中的版本 (Get selected versions)
        id: get-selected-versions
        run: |
          versions=()
          if [[ "${{ inputs.mc_1_21_1_21_8 }}" == "true" ]]; then versions+=("1.21-1.21.8"); fi
          if [[ "${{ inputs.mc_1_21_9_1_21_10 }}" == "true" ]]; then versions+=("1.21.9-1.21.10"); fi
          if [[ "${{ inputs.mc_1_20_6 }}" == "true" ]]; then versions+=("1.20.6"); fi
          if [[ "${{ inputs.mc_1_20_x }}" == "true" ]]; then versions+=("1.20.x"); fi
          if [[ "${{ inputs.mc_1_19_x }}" == "true" ]]; then versions+=("1.19.x"); fi
          if [[ "${{ inputs.mc_1_18_x }}" == "true" ]]; then versions+=("1.18.x"); fi
          if [[ "${{ inputs.mc_1_16_5 }}" == "true" ]]; then versions+=("1.16.5"); fi
          if [[ "${{ inputs.mc_1_12_2 }}" == "true" ]]; then versions+=("1.12.2"); fi
          IFS=,
          echo "Selected versions: ${versions[*]}"  # 打印选中的版本时也使用逗号分隔
          echo "versions=${versions[*]}" >> $GITHUB_OUTPUT

      - name: 设置矩阵 (Set matrix)
        id: set-matrix
        working-directory: .github/scripts
        env:
          GITHUB_SELECTED_VERSIONS: ${{ steps.get-selected-versions.outputs.versions }}
          GITHUB_RELEASE_ASSETS: ${{ steps.get-release-assets.outputs.asset_names }}
        run: |
          output=$(bun src/upload_modrinth.ts)
          echo "matrix=$output" >> $GITHUB_OUTPUT

      - name: 检查矩阵是否为空 (Check if matrix is empty)
        run: |
          if [ "${{ steps.set-matrix.outputs.matrix }}" = '{"include":[]}' ]; then
            echo "没有选择任何版本进行发布！"
            exit 1
          fi

  upload-to-modrinth:
    needs: setup
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v6

      - name: 下载 Release 里的文件 (Download files from Release)
        uses: robinraju/release-downloader@v1
        with:
          tag: "v${{ github.event.inputs.version }}"
          out-file-path: release_assets
          fileName: ${{ matrix.file }}

      - name: 获取 Release 正文 (Get Release Body)
        id: get-release-body
        run: |
          release_body=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ github.event.inputs.version }}" | jq -r .body)
          echo "release_body<<EOF" >> $GITHUB_ENV
          echo "$release_body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 上传到 Modrinth (Upload to Modrinth)
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: ./release_assets/${{ matrix.file }}
          name: ${{ matrix.name }}
          version: ${{ github.event.inputs.version }}
          changelog: ${{ env.release_body }}
          game_versions: ${{ matrix.game_versions }}
          release_type: release
          loaders: ${{ matrix.loader }}
          featured: true
          project_id: cPF7RWdR
        continue-on-error: true
